### ISSUE TITLE
앱 출시용 문서 작성 (하단의 내용보고 필요한 정보 작성)

### ISSUE THREAD

**Issue by taek0622** [JamongSoda/IntoHistory#123]
## ✅ 미리보기
(어떤 뷰 보여줄지 정해서 피그마로 작업 필요)
  - 미뉴 task #125  
 
<img width="822" alt="image" src="https://user-images.githubusercontent.com/96969693/185464282-8c76dd5d-43a8-4fa9-a2cf-0c37c01c4c85.png">

### 직접 걸으면서 만나는 대한민국의 영웅들, 영웅의 발자취를 따라 걸어서 역사속으로!

  - 당신의 영웅은 누구입니까? 당신의 영웅을 모아보세요~
  - 백일장!
  - 지: 잊지 말아야 할 나라를 지켜준 한국 인물들
  - 노: 직접 걸으면서 만나는 대한민국의 영웅들, 영웅의 발자취를 따라 걸어서 역사속으로!
  - 브: 직접 걸으면서 대한민국의 영웅들을 만나보세요.
  - 미:

### 🇰🇷 메인
칠판에서 매일 매일 새로운 역사상식을 배워보세요!

### 🇰🇷 영웅의 길
대한민국의 영웅들의 발자취를 따라가 보세요!
 - 전국방방 곳곳의 독립운동과 국가 수호와 관련 여행 코스를 확인할 수 있습니다.
- 코스 상세에서  탐방 목적 및 소요시간,  장소를 한눈에 확인할 수 있습니다.
- 장소 방문 시, 방문 여부를 실시간으로 체크하고 상세에서 방문한 장소를 확인할 수 있습니다.

### 🇰🇷대한민국의 영웅
대한민국의 자유를 위해 희생한 진정한 영웅들을 만나보세요!
- 코스 장소를 모두 방문하면, 영웅의 길 끝에서 대한민국의 영웅을 AR로 만날 수 있습니다.
- 영웅의 길 끝에서 만난 영웅들은 내 영웅 목록에서 당신을 기다리고 있습니다.
- 우리가 잊고 있던 영웅의 이야기를 궁금할때마다 확인할 수 있습니다.

## ✅ URL
https://hero-ad.notion.site/63f42753e1254bf9925d4cb00b28dd83

### 앱 심사에 도움이 될만한 부가 정보
  - ✅ 사용 데이터 관련 작성
  - ✅ 카메라 접근 왜
  - ✅ 알림 허용 왜?
  - ✅ 위치 왜?

 [접근 권한]
선택적 권한 제공에 동의하셔야 다음의 기능을 사용하실 수 있습니다.
- 위치:  지도첨부, 사용자의 위치정보 파악 및 위치기반 알림 서비스를 위해 위치 정보를 사용
- 알림: 사용자의 위치정보를 기반으로 장소 방문 여부 확인 알림을 주기 위해 알림 정보 허용
- 카메라: 카메라를 통해 AR 객체를 확인하기 위해 카메라 접근을 허용

[활용 데이터]
1. 데이터 이름 : 독립기념관_국내사적지_나라사랑역사의길
1.1 제공기관: 독립기념관
1.2 활용방법: 영웅의 길 코스를 조회하기 위해서 사용

2. 데이터 이름: 국가보훈처_이달의 독립운동가
2.1 제공기관: 국가보훈처
2.2 활용방법: 독립운동과 관련된 역사의 길을 지나면 독립운동가를 조회하고, 사용자가 직접 독립운동가의 정보를 확인할 수 있도록 함.

3. 데이터 이름: 국방부_전쟁기념관 행사정보
3.1 제공기관: 국방부
3.2 활용방법: 호국영웅에 대한 정보를 사용자가 직접 수집하고, 읽어볼 수 있게함.

4. 데이터 이름: 국방부_호국선열 정보
4.1 제공기관: 국방부
4.2 활용방법: 호국선열에 대한 정보를 사용자가 직접 수집하고, 읽어볼 수 있게함.

**Comment by deslog** [comment]
작성완료 ! 🥹
