### ISSUE TITLE
[Resource] 100MB이상의 대용량 PR을 위한 Git LFS(Large File Storage) 설치 (필수!!)

### ISSUE THREAD

**Issue by JUNY0110** [JamongSoda/IntoHistory#31]
### 설명

- Naver Map 라이브러리의 용량이 100MB가 넘는 관계로 IntoHistory프로젝트 사용자는 모두 Git LFS를 설치해주시기 바랍니다.
- [설치관련 참고 블로그 - 킥킥박사](https://blog.naver.com/PostView.naver?blogId=soojin_2604&logNo=222402500216&parentCategoryNo=&categoryNo=39&viewDate=&isShowPopularPosts=true&from=search)
- [Git-LFS에 대한 설명](https://newsight.tistory.com/330)

### 진행방법
1. Terminal에서 IntoHistory 프로젝트 파일 경로를 실행한다.
   a. GithubDesktop에서 실행 시 open in terminal을 하면 바로 켜짐.
2. [설치관련 참고 블로그 - 킥킥박사](https://blog.naver.com/PostView.naver?blogId=soojin_2604&logNo=222402500216&parentCategoryNo=&categoryNo=39&viewDate=&isShowPopularPosts=true&from=search)를 따라 Homebrew, git-lfs 설치.
   a. Home brew 설치: `bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`
   b. git-lfs설치: `brew install git-lfs`

**Comment by taek0622** [comment]
5번의 `git commit -m "커밋메시지"` 과정은 저희 Wiki [!!!필독](https://github.com/JamongSoda/IntoHistory/wiki/!!!%ED%95%84%EB%8F%85) 문서에 따라 `git commit`으로 입력 후 커밋 메시지를 작성하는 방식으로 하시면 더 편하게 작성하실 수 있습니다.

**Comment by deslog** [comment]
## ✅ check 
 - [ ] 에디
 - [ ] 노엘
 - [ ] 미뉴
 - [ ] 브라운
