### ISSUE TITLE
[Bug] CocoaPod 사용시 파일 추적이 계속 되는 버그

### ISSUE THREAD

**Issue by taek0622** [JamongSoda/IntoHistory#40]
### 설명

- Cocoapod 사용시 브랜치를 변경해도 파일이 계속 추적되어 같이 이동되는 버그 발생

### 우선순위

★★★★★

**Comment by JUNY0110** [comment]
이해를 돕기 위한 추가 설명)
Terminal에서 `git switch [브랜치명]`을 했을 때, 기존 브랜치의 내용을 전환할 브랜치로 전부 이동하게 되는 문제가 있습니다. 이를 해결하기 위한 내용입니다.

**Comment by taek0622** [comment]
> * 이해를 돕기 위한 추가 설명)
>   Terminal에서 `git switch [브랜치명]`을 했을 때, 기존 브랜치의 내용을 전환할 브랜치로 전부 이동하게 되는 문제가 있습니다. 이를 해결하기 위한 내용입니다.

살려주세요...🥲
