### ISSUE TITLE
[Resource] CocoaPods 설치방법

### ISSUE THREAD

**Issue by JUNY0110** [JamongSoda/IntoHistory#43]
### 설명

- 설치방법
0. 프로젝트 파일경로에서 Terminal 실행
1. 코코아팟 설치: `sudo gem install cocoapods`
2. Hombrew설치(git-lfs설치를 위함): `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"` 
3. git-lfs설치: `brew install git-lfs`
4. cocoapod 초기화: `pod init`
5. git-lfs 초기화: `git-lfs install`
6. 프로젝트 파일 경로 내의 Podfile을 열고 코드 추가
  `# Comment the nest line if you don't want to use dynamic frameworks use_frameworks!` 밑에  `pod 'NMapsMap'` 추가
<img width="489" alt="스크린샷 2022-08-11 오후 5 47 30" src="https://user-images.githubusercontent.com/98405970/184097116-7ac3d6c1-93d7-44fa-b4d0-b1e5de6b7ef4.png">

7. `pod install --repo-update` (안되면 `pod install`만 해주세요)

**Comment by deslog** [comment]
브라운 무사히 설치 완료 ✅

**Comment by taek0622** [comment]
해당 태스크는 모두가 수행한 것으로 보이므로 Close 하겠습니다.
혹시 나중에 다시 봐야할 경우가 발생할 수 있으므로 Issue Pin 해놓았으니 필요하시면 Issue 상단의 Pin한 Issue 목록에서 찾아 들어오시면 될 것 같습니다.
